---
# Adds simox ppa + install
# ppa seems broken for ubuntu 12.04...
#- name: Add simox ppa
#  apt_repository: repo='ppa:simox-dev/
#- name: Update package lists
#  apt: update_cache=yes

#- name: Install simox
#  apt: name={{item}} install_recommends=no
#  with_items:
#    - simox

- name: Test for Simox
  stat: path=/usr/local/include/VirtualRobot/Robot.h
  register: simox_exists

- name: Install subversion
  apt: name={{item}}
  with_items:
    - subversion
  when: not simox_exists.stat.exists

- name: Checkout Simox
  subversion: repo=https://svn.code.sf.net/p/simox/code/tags/release-2.3.1
              dest={{ simox_build_dir }}
  sudo: yes
  when: not simox_exists.stat.exists

- name: Install dependencies
  apt: name={{item}}
  with_items:
    - cmake
    - libboost-all-dev
    - libeigen3-*
    - libqt4-core
    - libqt4-gui
    - libqt4-dev
    - libqt4-designer
    - qt4-qmake
    - libcoin60-dev
    - libsoqt4-dev
  when: not simox_exists.stat.exists

- name: Create simox build directory {{ simox_build_dir }}/build
  file: state=directory path={{ simox_build_dir }}/build
  sudo: yes
  when: not simox_exists.stat.exists

- name: Build and Install
  shell: bash -c "cmake .. && make && sudo make install"
         chdir={{ simox_build_dir }}/build
  sudo: yes
  when: not simox_exists.stat.exists

- name: Clean up Simox
  file: state=absent path={{ simox_build_dir }}
  sudo: yes
  when: not simox_exists.stat.exists
