---
# vars file for glassbot
ros_release: 'hydro'
ros_user: 'glassbot'
ros_user_comment: 'Glass Bot'
ros_user_password: 'glassbot'
ros_user_email: 'software@shadowrobot.com'
ros_workspace_install: "../data/glassbot-{{ros_release}}.rosinstall"
ros_build_workspace: "~{{ros_user}}/rosbuild_{{ros_release}}_ws"
