---

- name: Check if sr-config is installed
  stat: path={{ros_workspace}}/src/sr_config
  register: sr_config_path

- name: Checkout or create the config branch
  shell: git checkout '{{ config_branch }}'
         chdir={{ros_workspace}}/src/sr_config
  sudo: yes
  sudo_user: "{{ros_user}}"
  when: sr_config_path.stat.exists

- name: Adds the user to dialout
  shell: usermod -a -G dialout '{{ros_user}}'
  sudo: yes
