---
# Playbook for codecov

- name: check if codecov_secure variable was set
  fail: msg="Variable codecov_secure was not set"
  when: (codecov_secure is not defined) or (codecov_secure == "")

- name: check if code_coverage_results_dir variable was set by build server
  fail: msg="Variable code_coverage_results_dir was not set by CI server"
  when: code_coverage_results_dir is not defined

- name: Send data to codecov
  shell: bash -c "cd {{repo_sources_path}} && bash <(curl -s https://codecov.io/bash) -f {{code_coverage_results_dir}}/coverage.cpp.xml -f {{code_coverage_results_dir}}/coverage.python.xml"
  environment:
        CODECOV_TOKEN: "{{codecov_secure}}"
